PATHIE_EXTRACTION = "PathIE"
PATHIE_STANZA_EXTRACTION = "PathIEStanza"
OPENIE_EXTRACTION = "OpenIE"
OPENIE51_EXTRACTION = "OpenIE51"
OPENIE6_EXTRACTION = "OpenIE6"
COSENTENCE_EXTRACTION = "COSentence"

OPENIE_EXTRACTIONS = [OPENIE_EXTRACTION, OPENIE51_EXTRACTION, OPENIE6_EXTRACTION]